In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('./육회test.csv',encoding = 'utf-8-sig')

In [2]:
print(df)
df.describe()

     Unnamed: 0                                              상품명     가격  \
0             1                         백십일 무료배송 한우 육회 당일도축 200g  24900
1             2                     삼형제고기 육회고기 220g 우둔살육회 한우육사시미  12900
2             3  한우 1등급 18종 꽃등심 새우살 살치살 육회 갈비살 등심 안심 채끝 차돌박이 국거리  19800
3             4         한우 암소 투플러스 우둔살 보섭살 육사시미 육회 뭉티기 한우생고기 1++  18000
4             5                현덕축산 국내산 숙성 육회 사시미 300g/500g (냉장)   9600
..          ...                                              ...    ...
295         296                         한우암소 1등급 육회 300g 육회소스 포함  22360
296         297                                    마장동한우 육회 한우투뿔  28500
297         298                           국내산 한우 1등급 소고기 육회 250g  20600
298         299                             [이룸축산] 한우1등급 육회 200g  17120
299         300                              [참다올]한우 1등급 육회 180g  13630

         리뷰    구매건수  찜하기  스마트스토어     쇼핑몰   배송비               용도     부위    중량  \
0     860.0  1590.0  814       1     백십일     0              육회용     우둔  200g
1    8337.0  2377.0  333       1   삼형제고기  3500              육회용     우둔  220g
2    2113.0  1683.0  336       1   건화한우다  3500              구이용     등심  200g
3     856.0  1085.0  412       1  소문난정육점  3000  육회용, 불고기용, 장조림용     우둔  300g
4    5368.0     NaN  124       0    현덕축산  3500              육회용  우둔,설도  300g
..      ...     ...  ...     ...     ...   ...              ...    ...   ...
295     NaN     NaN    0       0    인터파크  3000              NaN    NaN   NaN
296     NaN     NaN    0       0    11번가  3000              NaN    NaN   NaN
297     NaN     NaN    0       0    인터파크  3500              NaN    NaN   NaN
298     NaN     NaN    0       0    인터파크     0              NaN    NaN   NaN
299     NaN     NaN    0       0    11번가  3000              NaN    NaN   NaN

      등급                                                 링크
0    NaN  https://cr.shopping.naver.com/adcr.nhn?x=xQU6i...
1    NaN  https://cr.shopping.naver.com/adcr.nhn?x=KvE%2...
2    NaN  https://cr.shopping.naver.com/adcr.nhn?x=BQxfO...
3    NaN  https://cr.shopping.naver.com/adcr.nhn?x=rfDEC...
4    NaN  https://cr.shopping.naver.com/adcr.nhn?x=HPVmO...
..   ...                                                ...
295  NaN  https://cr.shopping.naver.com/adcr.nhn?x=rJeRD...
296  NaN  https://cr.shopping.naver.com/adcr.nhn?x=8gT7E...
297  NaN  https://cr.shopping.naver.com/adcr.nhn?x=OQcRf...
298  NaN  https://cr.shopping.naver.com/adcr.nhn?x=V4UF3...
299  NaN  https://cr.shopping.naver.com/adcr.nhn?x=JEvLI...

[300 rows x 14 columns]

,Unnamed: 0,가격,리뷰,구매건수,찜하기,스마트스토어,배송비
count,300.000000,300.000000,208.000000,98.000000,300.000000,300.000000,300.000000
mean,150.500000,23067.886667,389.004808,430.316327,50.423333,0.503333,2579.000000
std,86.746758,11101.171784,1231.285105,1043.040486,180.542542,0.500824,1556.169833
min,1.000000,1800.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,75.750000,14900.000000,7.000000,14.500000,0.000000,0.000000,0.000000
50%,150.500000,20000.000000,31.500000,42.500000,0.000000,1.000000,3300.000000
75%,225.250000,28742.500000,173.750000,275.250000,12.000000,1.000000,3500.000000
max,300.000000,64370.000000,8337.000000,5991.000000,1533.000000,1.000000,5000.000000

In [7]:
df = df.rename(columns={'Unnamed: 0':'랭킹'})
df = df.drop(df[(df['스마트스토어'] == 0)].index)
df = df.dropna(subset=['리뷰'])
df = df.drop(df[(df['랭킹'] > 50) & (df['리뷰'] < 30)].index)

In [9]:
df.to_csv('./육회test1.csv',encoding='utf-8-sig')